FROM mosaik/orch-base:v1

ARG SCENARIO_FILE
ARG EXTRA

### Add additional packages and simulators here.
### e.g.: RUN pip install mosaik-csv==1.0.3

COPY $SCENARIO_FILE .
COPY $EXTRA .
ENTRYPOINT python $SCENARIO_FILE
