FROM python:3.6

RUN apt-get update

### mosaik orchestrator base
RUN pip install --upgrade pip
RUN pip install mosaik~=2.6.0 mosaik-api~=2.4.2 simpy~=3.0.13 simpy.io~=0.2.3

WORKDIR /mosaik

ENV PYTHONDONTWRITEBYTECODE=1
